### ISSUE TITLE
Must validate the Notes inputs

### ISSUE THREAD

**Issue by bineetNaidu** [Posandu/devenv#1] opened 2022-02-28 07:24 UTC
hey, I was trying out your app by making some notes and markdowns but unfortunately, it breaks if you use invalid markdown syntax, and thats okay but the problem is you should be validating the input on the FrontEnd displaying it to the user on the UI. Since your not validating those its breaks your app.

Error Message on Screen: `Application error: a client-side exception has occurred (see the browser console for more information).`  

Error Message On Console: `Unknown language: `strike~~~` is not registered
    at n (838-4716e5f61ac1e2aa.js:28:186088)
    at Object.he [as highlight] (838-4716e5f61ac1e2aa.js:28:186275)
    at 838-4716e5f61ac1e2aa.js:28:292348
    at 838-4716e5f61ac1e2aa.js:28:325308
    at node (element<code>) (838-4716e5f61ac1e2aa.js:28:324925)
    at node (element<pre>) (838-4716e5f61ac1e2aa.js:28:325085)
    at node (root) (838-4716e5f61ac1e2aa.js:28:325085)
    at i (838-4716e5f61ac1e2aa.js:28:325165)
    at o (838-4716e5f61ac1e2aa.js:28:325258)
    at 838-4716e5f61ac1e2aa.js:28:291735
overrideMethod @ react_devtools_backend.js:4061
pe @ main-96060e10e65c9c86.js:1
fn @ main-96060e10e65c9c86.js:1
value @ main-96060e10e65c9c86.js:1
a.componentDidCatch.n.callback @ framework-91d7f78b5b4003c8.js:1
fa @ framework-91d7f78b5b4003c8.js:1
hu @ framework-91d7f78b5b4003c8.js:1
Li @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Ti @ framework-91d7f78b5b4003c8.js:1
vi @ framework-91d7f78b5b4003c8.js:1
(anonymous) @ framework-91d7f78b5b4003c8.js:1
t.unstable_runWithPriority @ framework-91d7f78b5b4003c8.js:1
$l @ framework-91d7f78b5b4003c8.js:1
Ql @ framework-91d7f78b5b4003c8.js:1
Hl @ framework-91d7f78b5b4003c8.js:1
Me @ framework-91d7f78b5b4003c8.js:1
Xt @ framework-91d7f78b5b4003c8.js:1
c @ rocket-loader.min.js:1
`

**Comment by Posandu** [comment] 2022-02-28 07:58
Hey @bineetNaidu Thanks for the issue! I can't reproduce it. Can you show me what you wrote?

**Comment by bineetNaidu** [comment] 2022-02-28 08:13
just add any invalid markdown syntax to your markdown editor to add it. In my case i wrote -> `~~~strike~~~`.

it was not something I did with purpose just trying what your markdown editor supports and I happened to forgot the strike-through syntax and guessed something wrong and it broke.

**Comment by Posandu** [comment] 2022-02-28 08:15
Oh. Will check that

**Comment by Posandu** [comment] 2022-02-28 08:16
Thanks I reproduced it. 
![image](https://user-images.githubusercontent.com/76736580/155948219-71e6e8fb-3549-4c20-a9f7-e3937cff5357.png)
will fix it soon

**Comment by bineetNaidu** [comment] 2022-02-28 10:38
:v:

**Comment by Posandu** [comment] 2022-02-28 12:58
Fixed in https://github.com/Posandu/devenv/commit/517751082f1707057f6d52521b079c79137828bb

**Closed as completed by Posandu** 2022-02-28 12:58 UTC
